//! Scheduled security report: a self-contained HTML page (print it to PDF
//! from any browser) summarising a network over a period.

use crate::engine::{Alert, DeviceSummary, Severity};
use crate::exposure::CheckResult;
use crate::store::StoreStats;
use chrono::{DateTime, Duration, Local, Utc};
use std::collections::BTreeMap;
use std::fmt::Write;

pub struct ReportData {
    pub network: String,
    pub days: u32,
    pub devices: Vec<DeviceSummary>,
    pub alerts: Vec<Alert>,
    pub compliance: Vec<CheckResult>,
    pub store: StoreStats,
    pub indicators: usize,
    pub signatures: usize,
}

fn esc(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn sev(s: Severity) -> &'static str {
    match s {
        Severity::Info => "info",
        Severity::Low => "low",
        Severity::Medium => "medium",
        Severity::High => "high",
        Severity::Critical => "critical",
    }
}

fn when(t: DateTime<Utc>) -> String {
    t.with_timezone(&Local).format("%b %-d, %H:%M").to_string()
}

pub fn render(d: &ReportData) -> String {
    let now = Utc::now();
    let since = now - Duration::days(d.days as i64);
    let alerts: Vec<&Alert> = d.alerts.iter().filter(|a| a.ts >= since).collect();
    let new_devices: Vec<&DeviceSummary> =
        d.devices.iter().filter(|x| x.first_seen >= since).collect();
    let mut by_sev: BTreeMap<Severity, usize> = BTreeMap::new();
    let mut by_rule: BTreeMap<String, usize> = BTreeMap::new();
    let mut by_tech: BTreeMap<String, usize> = BTreeMap::new();
    for a in &alerts {
        *by_sev.entry(a.severity).or_default() += 1;
        *by_rule.entry(a.rule.clone()).or_default() += 1;
        if let (Some(id), Some(n)) = (&a.mitre_id, &a.mitre_name) {
            *by_tech.entry(format!("{id} {n}")).or_default() += 1;
        }
    }
    let open = alerts.iter().filter(|a| !a.acknowledged).count();
    let mut risky: Vec<&DeviceSummary> = d.devices.iter().filter(|x| x.risk > 0).collect();
    risky.sort_by_key(|x| std::cmp::Reverse(x.risk));
    let failing: Vec<&CheckResult> = d
        .compliance
        .iter()
        .filter(|c| !c.failing.is_empty())
        .collect();

    let mut h = String::new();
    let _ = write!(
        h,
        r#"<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Niv.ON security report — {net}</title>
<style>
:root{{--ink:#18181b;--dim:#5b5b63;--rule:#e4e4e7;--crit:#b42318;--high:#c2410c;--med:#a16207;--low:#3f6212}}
body{{font:14px/1.5 -apple-system,"Segoe UI",system-ui,sans-serif;color:var(--ink);background:#fff;max-width:960px;margin:32px auto;padding:0 20px}}
h1{{font-size:26px;margin:0}} h2{{font-size:17px;margin:28px 0 8px;border-bottom:1px solid var(--rule);padding-bottom:6px}}
.sub{{color:var(--dim)}} table{{width:100%;border-collapse:collapse;margin:6px 0}} td,th{{text-align:left;padding:6px 8px;border-bottom:1px solid var(--rule);vertical-align:top}}
th{{font-size:11px;text-transform:uppercase;letter-spacing:.04em;color:var(--dim)}} .r{{text-align:right}} .mono{{font-family:ui-monospace,Menlo,monospace;font-size:12px}}
.kpis{{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}} .kpi{{border:1px solid var(--rule);border-radius:6px;padding:12px}} .kpi b{{font-size:24px;display:block}}
.sev{{font-weight:600;text-transform:capitalize}} .critical{{color:var(--crit)}} .high{{color:var(--high)}} .medium{{color:var(--med)}} .low{{color:var(--low)}} .info{{color:var(--dim)}}
@media print{{body{{margin:0}} h2{{break-after:avoid}} tr{{break-inside:avoid}}}}
</style></head><body>
<h1>Network security report</h1>
<div class="sub">{net} · last {days} day{s} ({from} – {to}) · generated by Niv.ON</div>
<div class="kpis">
<div class="kpi"><b>{nd}</b>devices ({nn} new)</div>
<div class="kpi"><b>{na}</b>alerts ({open} still open)</div>
<div class="kpi"><b>{nr}</b>devices at risk</div>
<div class="kpi"><b>{nf}</b>failing compliance checks</div>
</div>"#,
        net = esc(&d.network),
        days = d.days,
        s = if d.days == 1 { "" } else { "s" },
        from = when(since),
        to = when(now),
        nd = d.devices.len(),
        nn = new_devices.len(),
        na = alerts.len(),
        open = open,
        nr = risky.len(),
        nf = failing.len()
    );

    h.push_str(
        "<h2>Alerts by severity</h2><table><tr><th>Severity</th><th class=r>Alerts</th></tr>",
    );
    for (s, n) in by_sev.iter().rev() {
        let _ = write!(
            h,
            "<tr><td class='sev {c}'>{c}</td><td class=r>{n}</td></tr>",
            c = sev(*s)
        );
    }
    if by_sev.is_empty() {
        h.push_str("<tr><td colspan=2 class=sub>No alerts in this period.</td></tr>");
    }
    h.push_str("</table>");

    if !by_tech.is_empty() {
        h.push_str("<h2>MITRE ATT&amp;CK techniques observed</h2><table><tr><th>Technique</th><th class=r>Alerts</th></tr>");
        let mut t: Vec<_> = by_tech.into_iter().collect();
        t.sort_by_key(|(_, n)| std::cmp::Reverse(*n));
        for (k, n) in t {
            let _ = write!(h, "<tr><td>{}</td><td class=r>{n}</td></tr>", esc(&k));
        }
        h.push_str("</table>");
    }

    h.push_str("<h2>Highest-risk devices</h2><table><tr><th>Device</th><th>Type</th><th>Address</th><th>Priority</th><th class=r>Risk</th><th class=r>Open alerts</th></tr>");
    for x in risky.iter().take(15) {
        let _ = write!(
            h,
            "<tr><td>{}</td><td>{}</td><td class=mono>{}</td><td>{:?}</td><td class=r>{}</td><td class=r>{}</td></tr>",
            esc(&x.label),
            esc(&x.class),
            x.ips.iter().find(|i| i.is_ipv4()).map(|i| i.to_string()).unwrap_or_else(|| x.mac.to_string()),
            x.priority,
            x.risk,
            x.open_alerts
        );
    }
    if risky.is_empty() {
        h.push_str("<tr><td colspan=6 class=sub>No device carries risk.</td></tr>");
    }
    h.push_str("</table>");

    h.push_str("<h2>Most significant alerts</h2><table><tr><th>When</th><th>Severity</th><th>Alert</th><th>Status</th></tr>");
    let mut top: Vec<&&Alert> = alerts.iter().collect();
    top.sort_by(|a, b| b.severity.cmp(&a.severity).then(b.ts.cmp(&a.ts)));
    for a in top.iter().take(25) {
        let _ = write!(
            h,
            "<tr><td class=mono>{}</td><td class='sev {c}'>{c}</td><td><b>{}</b><div class=sub>{}</div></td><td>{:?}</td></tr>",
            when(a.ts),
            esc(&a.title),
            esc(&a.message),
            a.status,
            c = sev(a.severity)
        );
    }
    h.push_str("</table>");

    h.push_str("<h2>Compliance</h2><table><tr><th>Check</th><th>Severity</th><th>Failing devices</th></tr>");
    for c in &d.compliance {
        let names: Vec<String> = c.failing.iter().take(8).map(|(_, l, _)| esc(l)).collect();
        let _ = write!(
            h,
            "<tr><td><b>{}</b><div class=sub>{}</div></td><td class='sev {s}'>{s}</td><td>{}</td></tr>",
            esc(c.name),
            esc(c.description),
            if c.failing.is_empty() { "<span class=sub>none — pass</span>".to_string() } else { format!("{}{}", names.join(", "), if c.failing.len() > 8 { format!(" +{}", c.failing.len() - 8) } else { String::new() }) },
            s = sev(c.severity)
        );
    }
    h.push_str("</table>");

    if !new_devices.is_empty() {
        h.push_str("<h2>New devices</h2><table><tr><th>First seen</th><th>Device</th><th>Type</th><th>Vendor</th></tr>");
        for x in new_devices.iter().take(40) {
            let _ = write!(
                h,
                "<tr><td class=mono>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
                when(x.first_seen),
                esc(&x.label),
                esc(&x.class),
                esc(x.vendor.as_deref().unwrap_or("—"))
            );
        }
        h.push_str("</table>");
    }

    let _ = write!(
        h,
        "<h2>Coverage</h2><table><tr><td>Connections logged</td><td class=r>{}</td></tr><tr><td>DNS lookups logged</td><td class=r>{}</td></tr><tr><td>Threat indicators loaded</td><td class=r>{}</td></tr><tr><td>Signatures loaded</td><td class=r>{}</td></tr></table></body></html>",
        d.store.connections, d.store.dns, d.indicators, d.signatures
    );
    h
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_escaped_html() {
        let d = ReportData {
            network: "Home <lab>".into(),
            days: 7,
            devices: vec![],
            alerts: vec![],
            compliance: vec![],
            store: StoreStats::default(),
            indicators: 3,
            signatures: 28,
        };
        let h = render(&d);
        assert!(h.starts_with("<!doctype html>"));
        assert!(h.contains("Home &lt;lab&gt;"));
        assert!(h.contains("No alerts in this period."));
    }
}
